// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfYy3QkQAYZKOzXxydSQ7oOKqZe1XWmkI',
    appId: '1:635215715134:web:3c6a011ee9f0b8ba7b2a6f',
    messagingSenderId: '635215715134',
    projectId: 'chat-app-85246',
    authDomain: 'chat-app-85246.firebaseapp.com',
    storageBucket: 'chat-app-85246.appspot.com',
    measurementId: 'G-Y6VV92E75Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKPaSB92S3M4sz10bjqdTIeVVAhfZwXhU',
    appId: '1:635215715134:android:b2688e20b60b22317b2a6f',
    messagingSenderId: '635215715134',
    projectId: 'chat-app-85246',
    storageBucket: 'chat-app-85246.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkmBMfHizPtkTfnc4PIHS0thlSs_5e9L0',
    appId: '1:635215715134:ios:f3d8a8c078cbaddd7b2a6f',
    messagingSenderId: '635215715134',
    projectId: 'chat-app-85246',
    storageBucket: 'chat-app-85246.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkmBMfHizPtkTfnc4PIHS0thlSs_5e9L0',
    appId: '1:635215715134:ios:c14f424526bfccbd7b2a6f',
    messagingSenderId: '635215715134',
    projectId: 'chat-app-85246',
    storageBucket: 'chat-app-85246.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
